const USER_SESSION_TIME_JWT = '5h';
const USER_SESSION_TIME_COOKIE = 1000 * 60 * 60 * 24 * 5;

const COMPANY_SELECTION_SESSION_TIME_JWT = '3m';
const COMPANY_SELECTION_SESSION_TIME_COOKIE = 1000 * 60 * 3;

const USER_SESSION_COOKIE_NAME = 'actor_access';
const COMPANY_SELECTION_SESSION_COOKIE_NAME = 'select_org';

const LOGIN_SUCCESSFUL_MSG = 'Login Successful';
const REGISTRATION_SUCCESSFUL_MSG = 'Registration Successful';


module.exports = {
    USER_SESSION_TIME_JWT,
    USER_SESSION_TIME_COOKIE,
    COMPANY_SELECTION_SESSION_TIME_JWT,
    COMPANY_SELECTION_SESSION_TIME_COOKIE,
    USER_SESSION_COOKIE_NAME,
    COMPANY_SELECTION_SESSION_COOKIE_NAME,
    LOGIN_SUCCESSFUL_MSG,
    REGISTRATION_SUCCESSFUL_MSG
};